[wasm] Perf pipeline - fix blazor_scenarios run for hybrid globalization (#92898)
* [wasm] Perf pipeline - fix blazor_scenarios run for hybrid globalization

Fails with:
```
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 487, in <module>
    __main(sys.argv[1:])
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 483, in __main
    main(CiSetupArgs(**vars(args)))
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 411, in main
    dotnet_version = dotnet.get_dotnet_version(target_framework_moniker, args.cli) if args.dotnet_versions == [] else args.dotnet_versions[0]
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/dotnet.py", line 581, in get_dotnet_version
    raise RuntimeError(
RuntimeError: Unable to determine the .NET SDK used for net8.0
```

This is because the definition didn't copy over the `--dotnet-versions
8.0.0` workaround needed for now. And this runs only once a week, so it
was discovered on Oct 2(Monday) even though it was merged on Sep
26(Friday).

* [wasm] Perf: run the hybrid-globalization job on runtime-wasm-perf also, for validation