Use portable instead of pdbonly to avoid error on windows with mono csc
The purpose of this test is simply to verify that a test case can use csc.  The mono csc can error with the following on Windows

error CS0041: Unexpected error writing debug information -- 'The version of Windows PDB writer is older than required: 'diasymreader.dll''

In our UnityLinker test suite we use the csc with mono instead of a system install csc from MSBuild.

To get around this, use /debug:portable which is supported by both and doesn't undermine the goal of the test

Commit migrated from https://github.com/dotnet/linker/commit/e10f8ecb503b9c81b4cddcb47989cf32accca3d6