Use properties for target versions for core and framework (#67717)
* Populate target framework versions for tasks, and generated nugets based

.. on other properties, instead of hardcoding the values.

* Version substitution for MonoTargets nuget

* Version substitution for MonoAOTCompiler nuget

* sendhelixhelp.proj: Ensure that DotNetCliVersion gets overridden, as

.. intended. This seems to have been broken by the condition being
removed in
https://github.com/dotnet/arcade/commit/cfdac3560f1c887780bac171df7c22f7805e6f40
from the `DotNetCliVersion` property, causing the value to always
overridden again to `6.0.100`.

And this breaks wasm aot/eat tests on helix:
```
/datadisks/disk1/work/A4EE08D9/p/build/wasm/WasmApp.Native.targets(569,5): error MSB4062: The "MonoAOTCompiler" task could not be loaded from the assembly /datadisks/disk1/work/A4EE08D9/p/build/MonoAOTCompiler/MonoAOTCompiler.dll. Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/datadisks/disk1/work/A4EE08D9/w/B3AE0955/e/publish/ProxyProjectForAOTOnHelix.proj]
/datadisks/disk1/work/A4EE08D9/p/build/wasm/WasmApp.Native.targets(569,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

* Fix build for net7.0

Fails with:
```
src/tests/tracing/eventpipe/common/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcSocket.cs(27,35): error CS0108: 'IpcSocket.AcceptAsync(CancellationToken)' hides inherited member 'Socket.AcceptAsync(CancellationToken)'. Use the new keyword if hiding was intended. [/__w/1/s/src/tests/tracing/eventpipe/common/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj]
```

* Fix some more target frameworks

* bump the workload sdk version

* Revert "sendhelixhelp.proj: Ensure that DotNetCliVersion gets overridden, as"

This reverts commit 426b4b19155d54a7f338140f4c87feec471b5d92.

Last update to Arcade's XHarnessRunner.targets unconditionally set
DotNetCliVersion, to workaround which this commit was added. But the
update in this PR changed DotNetCliPackageType to `aspnetcore-runtime`,
which makes the version from global.json - `6.0.100` incorrect for
aspnetcore.

And the next upcoming update will set versions explicitly and change the
DotNetCliPackageType back to `sdk`.

Instead, revert this. And don't use version from global.json for now,
instead relying on the version that xharnesrunner.targets sets.

Co-authored-by: Ankit Jain <radical@gmail.com>