Revert "Fix a warning in atomic.c."
This reverts commit mono/mono@1fdc8789a7f4bfc6fa7f67c126569765194a3b6c.

This breaks the ios build:

../../../../../mono/mono/utils/atomic.c: In function ‘InterlockedCompareExchange64’:
../../../../../mono/mono/utils/atomic.c:572: error: ‘spin’ undeclared (first use in this function)
../../../../../mono/mono/utils/atomic.c:572: error: (Each undeclared identifier is reported only once
../../../../../mono/mono/utils/atomic.c:572: error: for each function it appears in.)


Commit migrated from https://github.com/mono/mono/commit/eeef746ffcb539c2b85b49143fa8d62b5ffe39c8