[mono] merge wasm-threading-eventpipe into main (#68232)
Merge initial work on multi-threaded WebAssembly.

The normal wasm build is single-threaded.  There should be no functional changes to its behavior.

To enable a multi-threaded build pass `/p:WasmEnableThreads=true`.  See `src/mono/wasm/threads.md` for details.

The big changes are:
1. The normal ref assemblies related to threading retain `[UnsupportedOSPlatform("browser")]` attributes for various threading-related functions
2. In System.Private.CoreLib, the `[UnsupportedOSPlatform]` attributes are removed, and functions that used to always throw PNSE nwo do a runtime check using `System.Threading.Thread.IsThreadStartSupported` to check if threading is enabled in the current build. 
3. A new nuget `Microsoft.NET.WebAssembly.Threading` is created.  It contains experimental ref assemblies without the `[UnsupportedOSPlatform]` attributes.  The intention is that code opting into experimenting with multithreading will include this nuget by setting some property that will be used by the wasm MSBuild SDK to pick a multi-threaded runtime build and configure things appropriately.  (The SDK updates don't exist yet).
4. In the multi-threaded runtime we don't use Emscripten's "main thread" option (ie: the browser thread is the main one); we also continue to run certain runtime-internal jobs (finalizers, GC pump) on the main thread even in the multi-threaded runtime.

Remaining work is tracked in the related issue https://github.com/dotnet/runtime/issues/68162

---

* Initial changes for emscripten 2.0.34

* Use emcc-link.rsp in build targets

* Use updated docker images

* Fix compiler warnings

* Put `--profiling-funcs` to `_EmccLinkFlags`

* Fix build

    src/mono/mono/mini/mini-runtime.c:3407:25: error: ‘invoke’ undeclared (first use in this function); did you mean ‘revoke’?
       3407 |                         invoke = mono_marshal_get_runtime_invoke_dynamic ();

* Add shell to the environment

   Environment setting https://github.com/emscripten-core/emscripten/blob/2.0.34/src/settings.js#L616-L641

   From emscripten 2.0.25 release notes

    - Support for the 'shell' environment is now disabled by default.  Running under
      `d8`, `js`, or `jsc` is not something that most emscripten users ever want to
      do, so including the support code is, more often than not, unnecessary.  Users
      who want shell support can enable it by including 'shell' in `-s ENVIRONMENT`
      (#14535).

   Example of the the size increase for bench sample:

    -a---          12/10/2021  3:35 PM         382113 dotnet.js
    -a---          12/13/2021 10:37 AM         383589 dotnet.js

* Add emcc-link.rsp to PlatformManifestFileEntry

* Feedback

   https://github.com/emscripten-core/emscripten/blob/2fda25eea756c78c8cb024aa5b6c2b188bf7990f/src/settings.js#L1173-L1176

   -s EXPORT_ES6 is link option

* Bump emscripten version

* Bump llvm package version and use its libclang

* Use newer docker images with emscripten 3.1.1

* Remove unused variable

* Add runtime support for threads in the wasm build

   To enable, pass `/p:WasmEnableThreads` when building the runtime

   ./build.sh -Subset mono+libs -os Browser -arch wasm /p:WasmEnableThreads=true

* Prevent runtime from starting twice when loaded in a web worker

* Automatically populate the emscripten mainScriptUrlOrBlob property so that worker initialization can find dotnet.js

* Add compatibility shim so that emscripten's generated worker.js can properly get a Module instance, since we broke the API

* Checkpoint

* Bring back threadpool and add some tracing in diagnostics

* Add comments and fix a typo

* Introduce 'MonoObjectRef' ts type. Migrate mono_string_intern to not have a retval

* Checkpoint (strings are broken for some reason)

* Fix string interning

* Migrate ObjectToString and GetDateValue

* Checkpoint gc safe/unsafe region work

* More ref conversion

* Checkpoint (broken?)

* Fix missing method

* Fix incorrect signatures

* Fix lint

* Add new 'R' signature char for 'ref object'

* Remove AddEventListener and RemoveEventListener Checkpoint

* eslint fixes

* Update call_method signature to avoid passing raw object pointers

* Ref-ify one websocket API and fix types and incorrect rooting of two others

* Deprecation metadata

* More ref

* Remove outdated comments

* Convert typed_array_new to ref

* Add volatile modifiers, satisfy eslint

* Update src/mono/wasm/runtime/corebindings.c

* Missing conflict

* Fix build, set coop gc, and always copy dotnet.worker.js when it's around for apps

* Disable sample profiler, add some functions that were missing from katelyn's PR.

* Add safepoint around ep_rt_wait_event_set.  Tweak sample to explicitly exit wasm in order to properly flush event to the nettrace file (w/ rundown events).

* [gc] Start the GC Finalizer thread on threaded WASM

* [mono] add GC Unsafe in mono_assembly_load; remove in EventPipe

   Remove GC Unsafe hack in ep_rt_wait_event_set

* post-merge cleanup: delete duplicated definitions

* [sample] Env vars should be stringy

* updated dotnet.d.ts

* Add mono_threads_wasm_async_run_in_main_thread; do background work on main

   Don't start a finalizer thread

   Queue all background work to run on the main thread

* [mono] Fix non-threaded wasm build

* Add a System.Threading.Thread.WebAssembly.Threading ref assembly

* Update the browser sample to use System.Threading.Thread.WebAssembly.Threading

* Rationalize System.Threading.Thread build

   In CoreLib, never add the [UnsupportedOSPlatform("browser")] attribute. Rely on runtime checks (`ThrowIfNoThreadStart()`). In System.Threading.Thread ref assembly, always add the unsupported platform
attribute.  Add mismatches to ApiCompat baseline. In System.Threading.Thread.WebAssembly.Threading don't add the attributes, and also set DisablePackageBaselineValidation to prevent Restore from looking for a System.Threading.Thread.WebAssembly.Threading nuget (fixes in-tree ProjectReferences for testing)

* only turn on analyzers for the browser sample

   not all wasm samples

* Make a single Microsoft.NET.WebAssembly.Threading nupkg

   that holds all the special ref assemblies

* works: sample has ProjectReference to the Microsoft.NET.WebAssembly.Threading.proj

* Add System.Threading.ThreadPool.WebAssembly.Threading ref assembly

* ThreadPool: throw PNSE if no thread start

* Update wasm threads.md

* apicompat: correct warnings for System.Threading.ThreadPool

* Add dotnet.worker.js to the runtime pack; update PlatformManifestFileEntry

* [wasm] startup: detect Blazor dotnet.[version].[hash].js location

   Blazor injects a `<link rel="modulepreload" />` element into the header when it boots; detect it and extract the URL of the script.

   This is needed by Emscripten's dotnet.worker.js to run WorkerGlobalScope.importScripts

* one more fix to Microsoft.NET.WebAssembly.Threading

   Seems to be necessary in order for the resulting .nupkg not to reference non-existent nugets for the ProjectReferences

* rename sample to browser-mt-eventpipe

* bring back unmodified browser sample

   The multithreading sample is browser-mt-eventpipe

* update browser-mt-eventpipe sample to use ref assembly refs

   Referencing the rollup Microsoft.NET.WebAssembly.Threading.proj doesn't work (it ends up bundling the ref assemblies into the publish dir and breaking the app)

* Use correct ifdef in AppContext.AnyOS.cs

* [build] support WasmEnableThreads and WasmEnablePerfTracing

   These toplevel options either turn on multi-threading in general, or turn on multithreading only for eventpipe internals.

   For libraries these define `FeatureWasmThreads` and `FeatureWasmPerfTracing` properties and the `FEATURE_WASM_THREADS` and `FEATURE_WASM_PERFTRACING` compiler constants.

   For the native code, they control `DISABLE_THREADS` and `DISABLE_WASM_USER_THREADS` cmake and preprocessor settings.

* Only add the portable threadpool on wasm if threading is enabled

* rename browser-mt-eventpipe csproj and main assembly

   Give it a unique name distinct from Wasm.Browser.CJS.Sample.csproj

* fix /p:WasmEnableThreads=false build after merge

* now fix the WasmEnableThreads=true build

* we need two ThreadPoolBoundHandle implementation stubs

   one for PortableThreadPool when threads are enabled, one for single-threaded wasm

* Add a System.Diagnostics.Tracing ref assembly gated by FeatureWasmPerfTracing

* [eventpipe] use the correct cmake option name

   see src/mono/mono.proj

* revert debug printf and commented out code

* turn off additional logging

* hack: set FeatureWasmPerfTracing in the browser-mt-eventpipe sample

   It would be better to drive this (the inclusion of the tracing runtime component) from a user-visible flag. not the FeatureWasmPerfTracing implementation detail

* remove unused variable, remove unneeded configure checks, revert line damage; add better comment in export.ts

* Exclude Microsoft.NET.WebAssembly.Threading from testPackages.proj

* review feedback, Apply suggestions from code review

* Use a testPackages settings file to skip package runtime item verification

* remove unneeded Directory.Build.props for ref package

   since ti doesn't compile its own assembly, none of these properties are needed

* use one ProjectReference item to share metadata for the ref assemblies

* remove ProjectReference comment and NoTargetsDoNotReferenceOutputAssemblies prop

* Remove unneeded target

* packaging simplification

   - move `_ExperimentalUpdateFileVersion` target to packaging.targets, conditioned on a new `IsExperimentalRefAssembly` attribute.  (The target increments the file version of the ref assembly to make it easier to distinguish from the real non-experimental ref assembly)
   - Remove unneeded src subdirectories in ref assembly libraries
   - Move properties that are only used in the ref assembly projects directory into the projects and delete Directory.Build.props in the experimental ref assembly subdirectories.

* move and rename UpdateExperimentalRefAssemblyFileVersion target

   packages.targets is only included for IsPackable=true projects, and these ref assemblies are not packable.

* Assorted code review nits

* Don't build/pack the multi-threaded sample on single-threaded runtime

* remove gratuitous debug printfs

* Apply suggestions from code review

* merge followup: nullable is enabled by default now

* make eslint happy

* include wasm-config.h in wasm runtime host

* include wasm-config.h into the runtime pack

   fixes aot compilation

* Add wasm-config.h to manifest

* put wasm-config.h into include/wasm from the outset

* put back noExitRuntime replacement for CJS

Co-authored-by: Radek Doulik <radekdoulik@gmail.com>
Co-authored-by: Radek Doulik <radekdoulik@google.com>
Co-authored-by: Zoltan Varga <vargaz@gmail.com>
Co-authored-by: Steve Pfister <steve.pfister@microsoft.com>
Co-authored-by: Katelyn Gadd <kg@luminance.org>
Co-authored-by: Viktor Hofer <viktor.hofer@microsoft.com>