[linker] do not use System.IO.Path on assembly resource names
  - fixes dotnet/linker#37305

  - resource name can be general string and using it as path
    might throw

       System.ArgumentException: Illegal characters in path.

  - it would be possible to check for the path's invalid characters in
    the resource name. that would cause crossplatform issues
    though.

    various platforms have different invalid charactes sets for path
    names. for example using assembly built on mac with embedded
    linker blacklisting xml file, which's name contains characters in
    its filename which are invalid on windows. so the windows built
    app using that assembly would fail mysteriously, because the
    important parts wouldn't be preserved.

    thus we use just string comparison


Commit migrated from https://github.com/dotnet/linker/commit/30463dcc278cdc8dfb23196f0cb5ef064d521b1d